name: "Scheduled Cron Jobs"

on:
    schedule:
        # runs every week at 08:00 UTC
        - cron: "0 8 * * 1"
    workflow_dispatch: {}

jobs:
    run-ev-charging-growth:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run EV Charging Growth correlation
          run: |
            python main.py ev-charging-growth --months 5 --symbol PPLT
    
        - name: Commit and push
          run: |
            git config --global user.name "github-actions"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
            git add data.csv
            git diff --cached --quiet && echo "No changes to commit" || (
                git commit -m "chore: update data.csv"
                git push
            )

        env:
            OPENCHARGEMAP_API_KEY: ${{ secrets.OPENCHARGEMAP_API_KEY }}
            MARKETSTACK_API_KEY: ${{ secrets.MARKETSTACK_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
